// <auto-generated />
using System;
using Davivienda.Migrations.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Davivienda.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204061245_Adicion de campo ARE_FEC_CRE")]
    partial class AdiciondecampoARE_FEC_CRE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Area", b =>
                {
                    b.Property<Guid>("ARE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ARE_ID");

                    b.Property<string>("ARE_DES")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ARE_DES");

                    b.Property<bool>("ARE_EST")
                        .HasColumnType("bit")
                        .HasColumnName("ARE_EST");

                    b.Property<DateTimeOffset>("ARE_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ARE_FEC_CRE");

                    b.Property<DateTimeOffset>("ARE_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ARE_FEC_MOD");

                    b.Property<string>("ARE_NOM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ARE_NOM");

                    b.HasKey("ARE_ID");

                    b.ToTable("AREA", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.BitacoraFriccion", b =>
                {
                    b.Property<Guid>("BIT_FRI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BIT_FRI_ID");

                    b.Property<string>("BIT_FRI_DES")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BIT_FRI_DES");

                    b.Property<string>("BIT_FRI_EST")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BIT_FRI_EST");

                    b.Property<DateTimeOffset?>("BIT_FRI_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("BIT_FRI_FEC_CRE");

                    b.Property<DateTimeOffset?>("BIT_FRI_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("BIT_FRI_FEC_MOD");

                    b.Property<string>("BIT_FRI_NOM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BIT_FRI_NOM");

                    b.Property<Guid?>("FRI_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FRI_ID");

                    b.Property<Guid?>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("BIT_FRI_ID");

                    b.HasIndex("FRI_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("BITACORA_FRICCIONES", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.BitacoraSoluciones", b =>
                {
                    b.Property<Guid>("BIT_SOL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BIT_SOL_ID");

                    b.Property<string>("BIT_SOL_DES")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BIT_SOL_DES");

                    b.Property<string>("BIT_SOL_EST")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BIT_SOL_EST");

                    b.Property<DateTimeOffset?>("BIT_SOL_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("BIT_SOL_FEC_CRE");

                    b.Property<DateTimeOffset?>("BIT_SOL_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("BIT_SOL_FEC_MOD");

                    b.Property<string>("BIT_SOL_NOM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BIT_SOL_NOM");

                    b.Property<int?>("BIT_SOL_TIE_TOT_TRA")
                        .HasColumnType("int")
                        .HasColumnName("BIT_SOL_TIE_TOT_TRA");

                    b.Property<Guid?>("SOL_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SOL_ID");

                    b.Property<Guid?>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("BIT_SOL_ID");

                    b.HasIndex("SOL_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("BITACORA_SOLUCIONES", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Comentarios", b =>
                {
                    b.Property<Guid>("COM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COM_ID");

                    b.Property<string>("COM_COM")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("COM_COM");

                    b.Property<DateTimeOffset?>("COM_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("COM_FEC_CRE");

                    b.Property<DateTimeOffset?>("COM_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("COM_FEC_MOD");

                    b.Property<Guid?>("FRI_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FRI_ID");

                    b.Property<Guid?>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("COM_ID");

                    b.HasIndex("FRI_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("COMENTARIOS", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.DetalleProyecto", b =>
                {
                    b.Property<Guid>("DET_PRO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DET_PRO_ID");

                    b.Property<DateTimeOffset?>("DET_PRO_FEC_ASI")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DET_PRO_FEC_ASI");

                    b.Property<DateTimeOffset?>("DET_PRO_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DET_PRO_FEC_CRE");

                    b.Property<DateTimeOffset?>("DET_PRO_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DET_PRO_FEC_MOD");

                    b.Property<Guid>("PRO_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PRO_ID");

                    b.Property<Guid>("ROL_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ROL_ID");

                    b.Property<Guid>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("DET_PRO_ID");

                    b.HasIndex("PRO_ID");

                    b.HasIndex("ROL_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("DETALLES_PROYECTO", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Documentacion", b =>
                {
                    b.Property<Guid>("DOC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DOC_ID");

                    b.Property<DateTimeOffset?>("DOC_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DOC_FEC_CRE");

                    b.Property<DateTimeOffset?>("DOC_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DOC_FEC_MOD");

                    b.Property<string>("DOC_NOM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DOC_NOM");

                    b.Property<string>("DOC_RUT")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DOC_RUT");

                    b.Property<Guid?>("TAR_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAR_ID");

                    b.Property<Guid?>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("DOC_ID");

                    b.HasIndex("TAR_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("DOCUMENTACION", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Friccion", b =>
                {
                    b.Property<Guid>("FRI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FRI_ID");

                    b.Property<string>("FRI_DES")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FRI_DES");

                    b.Property<string>("FRI_EST")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FRI_EST");

                    b.Property<DateTimeOffset?>("FRI_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FRI_FEC_CRE");

                    b.Property<DateTimeOffset?>("FRI_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FRI_FEC_MOD");

                    b.Property<string>("FRI_IMP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FRI_IMP");

                    b.Property<string>("FRI_TIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FRI_TIP");

                    b.Property<Guid?>("TAR_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAR_ID");

                    b.Property<Guid?>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("FRI_ID");

                    b.HasIndex("TAR_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("FRICCION", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Notificaciones", b =>
                {
                    b.Property<Guid>("NOT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NOT_ID");

                    b.Property<DateTimeOffset?>("NOT_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("NOT_FEC_CRE");

                    b.Property<DateTimeOffset?>("NOT_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("NOT_FEC_MOD");

                    b.Property<bool>("NOT_LEI")
                        .HasColumnType("bit")
                        .HasColumnName("NOT_LEI");

                    b.Property<string>("NOT_MEN")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NOT_MEN");

                    b.Property<string>("NOT_TIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOT_TIP");

                    b.Property<Guid?>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("NOT_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("NOTIFICACIONES", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Prioridad", b =>
                {
                    b.Property<Guid>("PRI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PRI_ID");

                    b.Property<string>("PRI_DES")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PRI_DES");

                    b.Property<DateTimeOffset?>("PRI_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PRI_FEC_CRE");

                    b.Property<DateTimeOffset?>("PRI_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PRI_FEC_MOD");

                    b.Property<int?>("PRI_NIV")
                        .HasColumnType("int")
                        .HasColumnName("PRI_NIV");

                    b.Property<string>("PRI_NOM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRI_NOM");

                    b.HasKey("PRI_ID");

                    b.ToTable("PRIORIDAD", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Procesos", b =>
                {
                    b.Property<Guid>("PROC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PROC_ID");

                    b.Property<string>("PROC_DES")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PROC_DES");

                    b.Property<bool?>("PROC_EST")
                        .HasColumnType("bit")
                        .HasColumnName("PROC_EST");

                    b.Property<DateTimeOffset?>("PROC_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PROC_FEC_CRE");

                    b.Property<DateTimeOffset?>("PROC_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PROC_FEC_MOD");

                    b.Property<string>("PROC_FRE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PROC_FRE");

                    b.Property<string>("PROC_NOM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PROC_NOM");

                    b.Property<Guid?>("PRO_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PRO_ID");

                    b.HasKey("PROC_ID");

                    b.HasIndex("PRO_ID");

                    b.ToTable("PROCESO", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Proyectos", b =>
                {
                    b.Property<Guid>("PRO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PRO_ID");

                    b.Property<Guid?>("ARE_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ARE_ID");

                    b.Property<string>("PRO_DES")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRO_DES");

                    b.Property<string>("PRO_EST")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRO_EST");

                    b.Property<DateTimeOffset?>("PRO_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PRO_FEC_CRE");

                    b.Property<DateTimeOffset?>("PRO_FEC_FIN")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PRO_FEC_FIN");

                    b.Property<DateTimeOffset?>("PRO_FEC_INI")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PRO_FEC_INI");

                    b.Property<DateTimeOffset?>("PRO_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PRO_FEC_MOD");

                    b.Property<string>("PRO_NOM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PRO_NOM");

                    b.HasKey("PRO_ID");

                    b.HasIndex("ARE_ID");

                    b.ToTable("PROYECTO", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Roles", b =>
                {
                    b.Property<Guid>("ROL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ROL_ID");

                    b.Property<string>("ROL_DES")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROL_DES");

                    b.Property<bool>("ROL_EST")
                        .HasColumnType("bit")
                        .HasColumnName("ROL_EST");

                    b.Property<string>("ROL_NOM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ROL_NOM");

                    b.HasKey("ROL_ID");

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Soluciones", b =>
                {
                    b.Property<Guid>("SOL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SOL_ID");

                    b.Property<Guid?>("FRI_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FRI_ID");

                    b.Property<string>("SOL_DES")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SOL_DES");

                    b.Property<string>("SOL_EST")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SOL_EST");

                    b.Property<DateTimeOffset?>("SOL_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("SOL_FEC_CRE");

                    b.Property<DateTimeOffset?>("SOL_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("SOL_FEC_MOD");

                    b.Property<int?>("SOL_NIV_EFE")
                        .HasColumnType("int")
                        .HasColumnName("SOL_NIV_EFE");

                    b.Property<string>("SOL_NOM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SOL_NOM");

                    b.Property<DateTimeOffset?>("SOL_TIE_RES")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("SOL_TIE_RES");

                    b.Property<Guid?>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("SOL_ID");

                    b.HasIndex("FRI_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("SOLUCIONES", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Tarea", b =>
                {
                    b.Property<Guid>("TAR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAR_ID");

                    b.Property<Guid?>("PRI_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PRI_ID");

                    b.Property<Guid?>("PROC_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PROC_ID");

                    b.Property<string>("TAR_DES")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TAR_DES");

                    b.Property<string>("TAR_EST")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TAR_EST");

                    b.Property<DateTimeOffset?>("TAR_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("TAR_FEC_CRE");

                    b.Property<DateTimeOffset?>("TAR_FEC_FIN")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("TAR_FEC_FIN");

                    b.Property<DateTimeOffset?>("TAR_FEC_INI")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("TAR_FEC_INI");

                    b.Property<DateTimeOffset?>("TAR_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("TAR_FEC_MOD");

                    b.Property<string>("TAR_NOM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TAR_NOM");

                    b.Property<Guid?>("USU_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.HasKey("TAR_ID");

                    b.HasIndex("PRI_ID");

                    b.HasIndex("PROC_ID");

                    b.HasIndex("USU_ID");

                    b.ToTable("TAREA", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Usuario", b =>
                {
                    b.Property<Guid>("USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USU_ID");

                    b.Property<Guid?>("ROL_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ROL_ID");

                    b.Property<string>("USU_CON")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("USU_CON");

                    b.Property<string>("USU_COR")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USU_COR");

                    b.Property<bool?>("USU_EST")
                        .HasColumnType("bit")
                        .HasColumnName("USU_EST");

                    b.Property<DateTimeOffset?>("USU_FEC_CRE")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("USU_FEC_CRE");

                    b.Property<DateTimeOffset?>("USU_FEC_MOD")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("USU_FEC_MOD");

                    b.Property<string>("USU_NOM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USU_NOM");

                    b.Property<string>("USU_NUM")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("USU_NUM");

                    b.Property<string>("USU_TEL")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("USU_TEL");

                    b.HasKey("USU_ID");

                    b.HasIndex("ROL_ID");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.BitacoraFriccion", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Friccion", "Friccion")
                        .WithMany()
                        .HasForeignKey("FRI_ID");

                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID");

                    b.Navigation("Friccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.BitacoraSoluciones", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Soluciones", "Solucion")
                        .WithMany()
                        .HasForeignKey("SOL_ID");

                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID");

                    b.Navigation("Solucion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Comentarios", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Friccion", "Friccion")
                        .WithMany()
                        .HasForeignKey("FRI_ID");

                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID");

                    b.Navigation("Friccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.DetalleProyecto", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Proyectos", "Proyecto")
                        .WithMany()
                        .HasForeignKey("PRO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Davivienda.Migrations.ModelosEF.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("ROL_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Documentacion", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TAR_ID");

                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Friccion", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TAR_ID");

                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Notificaciones", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Procesos", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Proyectos", "Proyecto")
                        .WithMany()
                        .HasForeignKey("PRO_ID");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Proyectos", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Area", "Area")
                        .WithMany()
                        .HasForeignKey("ARE_ID");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Soluciones", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Friccion", "Friccion")
                        .WithMany()
                        .HasForeignKey("FRI_ID");

                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID");

                    b.Navigation("Friccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Tarea", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Prioridad", "Prioridad")
                        .WithMany("Tareas")
                        .HasForeignKey("PRI_ID");

                    b.HasOne("Davivienda.Migrations.ModelosEF.Procesos", "Proceso")
                        .WithMany("Tareas")
                        .HasForeignKey("PROC_ID");

                    b.HasOne("Davivienda.Migrations.ModelosEF.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("USU_ID");

                    b.Navigation("Prioridad");

                    b.Navigation("Proceso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Usuario", b =>
                {
                    b.HasOne("Davivienda.Migrations.ModelosEF.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("ROL_ID");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Prioridad", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Davivienda.Migrations.ModelosEF.Procesos", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
